language: minimal

jobs:
  include:
    - language: python
      python: 2.7
      env: BUILD_TYPE=bare_machines
    - language: python
      python: 3.5
      env: BUILD_TYPE=bare_machines
    - language: python
      python: 3.6
      env: BUILD_TYPE=bare_machines
    - language: python
      python: 3.7
      env: BUILD_TYPE=bare_machines
    - language: python
      python: 3.8
      env: BUILD_TYPE=bare_machines
    - language: python
      python: 3.9
      env: BUILD_TYPE=bare_machines
    - language: minimal
      env: BUILD_TYPE=debian_sys_container
    - language: minimal
      env: PYTHON_VER=2.7 BUILD_TYPE=centos_containers
    - language: minimal
      env: PYTHON_VER=3.5 BUILD_TYPE=centos_containers
    - language: minimal
      env: PYTHON_VER=3.6 BUILD_TYPE=centos_containers
    - language: minimal
      env: PYTHON_VER=3.7 BUILD_TYPE=centos_containers
    - language: minimal
      env: PYTHON_VER=3.8 BUILD_TYPE=centos_containers
    - language: minimal
      env: PYTHON_VER=3.9 BUILD_TYPE=centos_containers
    - language: minimal
      env: PYTHON_VER=3.10 BUILD_TYPE=centos_containers
    - language: minimal
      env: PYTHON_VER=2.7 BUILD_TYPE=debian_containers
    - language: minimal
      env: PYTHON_VER=3.5 BUILD_TYPE=debian_containers
    - language: minimal
      env: PYTHON_VER=3.6 BUILD_TYPE=debian_containers
    - language: minimal
      env: PYTHON_VER=3.7 BUILD_TYPE=debian_containers
    - language: minimal
      env: PYTHON_VER=3.8 BUILD_TYPE=debian_containers
    - language: minimal
      env: PYTHON_VER=3.9 BUILD_TYPE=debian_containers
    - language: minimal
      env: PYTHON_VER=3.10 BUILD_TYPE=debian_containers
  allow_failures:
    - language: minimal
      env: PYTHON_VER=3.10 BUILD_TYPE=centos_containers
    - language: minimal
      env: PYTHON_VER=3.10 BUILD_TYPE=debian_containers

services:
    - docker

notifications:
  email:
    - buildout-development@googlegroups.com

script:
    - ./ci_build.sh
