name: Centos containers

on:
  workflow_run:
    workflows:
      - "Ubuntu 3.8"
    types:
      - completed
  # Allow to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    if: (github.event_name == 'workflow_dispatch') || ((github.event_name == 'workflow_run') && (github.event.workflow_run.conclusion == 'success'))
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["2.7", "3.5", "3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Test in container with Python ${{ matrix.python-version }}
      env:
        PYTHON_VER: ${{matrix.python-version}}
        BUILD_TYPE: centos_containers
      run: |
        ./ci_build.sh
